[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
reward_keys = "65BeAsYduu3X91yWbF9TQFj6EqD5TpqFyfWMEkrpdNZv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/smt50-keys/smt50deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
